# Generated by Django 4.1.7 on 2023-03-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order ID'),
        ),
    ]
