# Generated by Django 4.1.7 on 2023-03-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.CharField(blank=True, default=1, max_length=10, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
